version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app/
    container_name: TimeKeeper
    restart: unless-stopped
    environment:
      - PORT=$PORT
    ports:
      - "4000:4000"